### ISSUE TITLE
Could you provide an example of CheckboxGroup ?

### ISSUE THREAD

**Issue by funsunz** [wmzy/formsy-antd#3]
Following is my code:
```jsx
<Form>
  <FormItem required label="Fruit">
    <CheckboxGroup name="fruit" value={[]} options={[
        { label: 'Apple', value: 'Apple' },
        { label: 'Pear', value: 'Pear' },
        { label: 'Orange', value: 'Orange' }
      ]} />
  </FormItem>
</Form>
```
Then I checked a checkbox, and got an error:
`
Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
`

**Comment by wmzy** [comment]
Sorry!
There is a bug with new react version.
I just fixed it in the new version.
Run `npm i formsy-antd@2.0.0` update it.

**Comment by funsunz** [comment]
Thanks bro!
